### PR TITLE
Fix LIBART_IMG_HOST_BASE_ADDRESS unset

### PR DESCRIPTION
**Pull request by Tripyrex**
art/build/Android.common_build.mk:217: *** LIBART_IMG_HOST_BASE_ADDRESS unset. Stop.

### CODE REVIEW

**Comment by eousphoros** [comment]
Where are you seeing this error?

**Comment by lssjbrolli** [comment]
isn't that flag true by default?

@art/build/Android.common_build.mk

```
ifndef ANDROID_COMMON_BUILD_MK
ANDROID_COMMON_BUILD_MK = true

```

**Comment by Tripyrex** [comment]
@eousphoros :When i was compiling for AICP Lollipop 5.1,this error showed up all the time.

@lssjbrolli That flag is true by default however when i started compiling AICP without this commit,it keeps showing up the error that it was unset all the time.Pretty weird i guess

**Comment by schwabe93** [comment]
Hi @all getting this error for the Blisspop android 5.1 build:

target thumb C++: linker <= bionic/linker/linker_allocator.cpp
In file included from bionic/linker/linker.h:35:0,
                 from bionic/linker/debugger.cpp:29:
bionic/linker/debugger.cpp: In function 'int socket_abstract_client(const char*, int)':
bionic/linker/debugger.cpp:102:75: error: dereferencing type-punned pointer might break strict-aliasing ru                                                             les [-Werror=strict-aliasing]
   int rc = TEMP_FAILURE_RETRY(connect(s, reinterpret_cast<sockaddr*>(&addr), alen));
                                                                           ^
bionic/linker/debugger.cpp:102:75: error: dereferencing type-punned pointer might break strict-aliasing ru                                                             les [-Werror=strict-aliasing]
   int rc = TEMP_FAILURE_RETRY(connect(s, reinterpret_cast<sockaddr*>(&addr), alen));
                                                                           ^
cc1plus: all warnings being treated as errors
make: *** [/var/lib/jenkins/bliss5.1/out/target/product/klimtlte/obj/EXECUTABLES/linker_intermediates/debu                                                             gger.o] Error 1
make: *** Waiting for unfinished jobs....
target thumb C++: linker <= bionic/linker/linker_environ.cpp
bionic/linker/linker_allocator.cpp: In member function 'void LinkerBlockAllocator::create_new_page()':
bionic/linker/linker_allocator.cpp:106:76: error: dereferencing type-punned pointer will break strict-alia                                                             sing rules [-Werror=strict-aliasing]
   FreeBlockInfo* first_block = reinterpret_cast<FreeBlockInfo*>(page->bytes);
                                                                            ^
cc1plus: all warnings being treated as errors
make: *** [/var/lib/jenkins/bliss5.1/out/target/product/klimtlte/obj/EXECUTABLES/linker_intermediates/link                                                             er_allocator.o] Error 1

**Comment by schwabe93** [comment]
ok sorry i read it again an turn off strict aliasing i try it again

**Pull request closed without merging**
