### PR TITLE
Tweaks and fixes, or so i hope :)

### PR DESCRIPTION
**Pull request by lssjbrolli**

### CODE REVIEW

**Comment by schwabe93** [comment]
ok, the files are in my etc folder, do you had make a clean flash

**Comment by lssjbrolli** [comment]
yes, please post a logcat while trying to run youtube.

**Comment by schwabe93** [comment]
http://pastebin.com/J2JdU5Fg

**Comment by lssjbrolli** [comment]
what about other media? it's only happening in youtube or in media players too?

**Comment by lssjbrolli** [comment]
you can also push media_codecs.xml from the old build to check if it's that at fault

**Comment by schwabe93** [comment]
It happens on streaming movies, when i play videos from my sd card it works

**Comment by eousphoros** [comment]
Please continue to use descriptive commit messages so in the future it is easy to identify changes based on git log. Thank you for your continued work on this. Hoping to get back to this soon.

**Comment by lssjbrolli** [comment]
@eousphoros  did you manage to build cm-12.1? i get a log of api changes errors.

**Comment by eousphoros** [comment]
I haven't built t705 in awhile. Though I did just create a cm-12.1 branch. Do you have an example of an error?

**Comment by lssjbrolli** [comment]
```
frameworks/base/api/system-current.txt:25555: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Callable.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25556: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Callable.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25557: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Callable.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25570: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Contactables.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25571: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Contactables.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25572: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Contactables.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25586: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Email.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25587: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Email.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25588: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Email.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25599: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Event.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25600: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Event.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25601: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Event.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25610: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.GroupMembership.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25611: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.GroupMembership.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25612: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.GroupMembership.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25619: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Identity.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25620: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Identity.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25621: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Identity.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25633: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Im.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25634: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Im.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25635: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Im.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25654: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Nickname.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25655: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Nickname.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25656: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Nickname.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25668: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Note.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25669: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Note.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25670: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Note.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25680: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Organization.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25681: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Organization.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25682: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Organization.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25699: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Phone.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25700: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Phone.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25701: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Phone.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25730: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Photo.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25731: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Photo.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25732: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Photo.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25741: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Relation.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25742: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Relation.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25743: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Relation.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25765: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.SipAddress.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25766: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.SipAddress.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25767: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.SipAddress.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25777: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.StructuredName.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25778: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.StructuredName.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25779: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.StructuredName.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25799: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.StructuredPostal.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25800: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.StructuredPostal.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25801: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.StructuredPostal.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25815: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Website.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25816: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Website.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25817: error 10: Removed field android.provider.ContactsContract.CommonDataKinds.Website.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25877: error 10: Removed field android.provider.ContactsContract.Contacts.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25878: error 10: Removed field android.provider.ContactsContract.Contacts.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25879: error 10: Removed field android.provider.ContactsContract.Contacts.EXTRA_ADDRESS_BOOK_INDEX_TITLES
frameworks/base/api/system-current.txt:25926: error 10: Removed field android.provider.ContactsContract.Data.EXTRA_ADDRESS_BOOK_INDEX
frameworks/base/api/system-current.txt:25927: error 10: Removed field android.provider.ContactsContract.Data.EXTRA_ADDRESS_BOOK_INDEX_COUNTS
frameworks/base/api/system-current.txt:25928: error 10: Removed field android.provider.ContactsContract.Data.EXTRA_ADDRESS_BOOK_INDEX_TITLES

******************************
You have tried to change the API from what has been previously approved.

To make these errors go away, you have two choices:
   1) You can add "@hide" javadoc comments to the methods, etc. listed in the
      errors above.

   2) You can update current.txt by executing the following command:
         make update-api

      ^^^^^^^^^^^^^^^^^^
      NO. NO. STOP BEING LAZY. SERIOUSLY.
      DO NOT DO THIS in CM. THIS IS A LIE. IT WILL BREAK THINGS.

      To submit the revised current.txt to the main Android repository,
      you will need approval.
******************************
```

**Comment by lssjbrolli** [comment]
this is from a clean repo sync of cm-12.1

**Comment by schwabe93** [comment]
The media issue, i think is blisspop related. I build with the old audio/media sources and that worked also not.

**Pull request merged**
